// Parse a Claude Code session JSONL into a structured session model.
// Input:  path to a *.jsonl file under ~/.claude/projects/<project>/
// Output: normalized session with user messages, tool calls, file ops.

import { readFileSync } from 'node:fs';

export interface SessionTurn {
  uuid: string;
  role: 'user' | 'assistant';
  timestamp: number;                 // unix seconds
  text: string;                      // human-readable text (tool calls extracted into tool_calls[])
  tool_calls?: Array<{
    name: string;
    input: any;
    tool_use_id: string;
  }>;
  tool_results?: Array<{
    tool_use_id: string;
    is_error: boolean;
    output_preview: string;          // first 300 chars
  }>;
}

export interface ParsedSession {
  session_id: string;
  project_cwd: string;                // C:\Users\HP\Card_Navi
  started_at: number;
  ended_at: number;
  git_branch?: string;
  turns: SessionTurn[];
  file_ops: Array<{
    operation: 'read' | 'edit' | 'write' | 'bash' | 'other';
    path: string;                     // for file ops
    turn_uuid: string;
    timestamp: number;
    preceding_user_text: string;      // the user request immediately before (context)
    tool_input_preview: string;       // first 200 chars of the tool args
  }>;
  turn_count_user: number;
  turn_count_assistant: number;
  errors_count: number;
}

function extractTextFromContent(content: any): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  const parts: string[] = [];
  for (const block of content) {
    if (typeof block === 'string') { parts.push(block); continue; }
    if (block?.type === 'text' && typeof block.text === 'string') parts.push(block.text);
  }
  return parts.join('\n');
}

function extractToolCalls(content: any): SessionTurn['tool_calls'] {
  if (!Array.isArray(content)) return undefined;
  const calls: NonNullable<SessionTurn['tool_calls']> = [];
  for (const block of content) {
    if (block?.type === 'tool_use') {
      calls.push({ name: block.name, input: block.input, tool_use_id: block.id });
    }
  }
  return calls.length > 0 ? calls : undefined;
}

function extractToolResults(content: any): SessionTurn['tool_results'] {
  if (!Array.isArray(content)) return undefined;
  const results: NonNullable<SessionTurn['tool_results']> = [];
  for (const block of content) {
    if (block?.type === 'tool_result') {
      const rawOutput = typeof block.content === 'string'
        ? block.content
        : Array.isArray(block.content)
          ? block.content.map((c: any) => (typeof c === 'string' ? c : c?.text ?? '')).join('\n')
          : '';
      results.push({
        tool_use_id: block.tool_use_id,
        is_error: !!block.is_error,
        output_preview: rawOutput.slice(0, 300),
      });
    }
  }
  return results.length > 0 ? results : undefined;
}

// Detect noise messages we should skip for "meaningful user text"
export function isMetaOrNoise(text: string): boolean {
  if (!text) return true;
  const t = text.trim();
  if (t.length === 0) return true;
  if (t.startsWith('<local-command-caveat>')) return true;
  if (t.startsWith('<system-reminder>')) return true;
  if (t.startsWith('<command-message>')) return true;
  if (t.startsWith('<command-name>')) return true;
  if (t.startsWith('<scheduled-task')) return true;            // cron-triggered, no real user intent
  if (t.startsWith('<automated-')) return true;                // other automation wrappers
  if (t.startsWith('<bash-') || t.startsWith('<ide-')) return true;
  if (t.startsWith('<task-notification>')) return true;        // background task completion notices
  if (t.startsWith('<local-command-stdout>')) return true;     // shell command output capture
  if (t.startsWith('<local-command-stderr>')) return true;
  if (t.startsWith('<command-stdout>') || t.startsWith('<command-stderr>')) return true;
  // Claude Code's auto-injected context-continuation summaries — these are NOT user warnings
  if (t.startsWith('This session is being continued from a previous conversation')) return true;
  if (t.includes('Caveat: The messages below were generated by the user while running local commands')) return true;
  if (t.match(/^\/(compact|clear|exit|help|quit|login|logout|mcp)(\s|$)/)) return true;
  // Reminders that are pure tool hints
  if (t.includes('The TodoWrite tool hasn\'t been used recently')) return true;
  if (t.includes('PostToolUse:Write hook')) return true;
  return false;
}

// Detect content that's clearly a paste-back of assistant output / external system text,
// not the user's own thought. Stricter than isMetaOrNoise — used for caveat/learning extraction
// where we want only authentic user reflection, not pasted material.
export function isPastedExternalContent(text: string): boolean {
  if (!text) return false;
  const t = text.trim();
  // Assistant-style bullet/result markers at start
  if (/^[●○◯◆■▶►]\s/.test(t)) return true;
  if (/^Attempt #\d+ failed/i.test(t)) return true;
  // Box-drawing characters (table dumps from CLI)
  if (/[┌┐└┘├┤┬┴┼━─│]/.test(t.slice(0, 200)) && t.length > 100) return true;
  // System prompts being pasted in
  if (/^You are (a|an|the) [A-Z]\w+/.test(t)) return true;
  // Marketing emails / docs
  if (/^(Welcome to|Hey there,|Hi there,|Dear)\s/i.test(t)) return true;
  if (/^(Add|Enable|Disable|Configure) (organization|2FA|members|users)/i.test(t)) return true;
  // Service status pages / logs
  if (/^(Service offline|Failed|Success|Deployment|Build|Logs?|Error:)/.test(t.slice(0, 80))) return true;
  // Extractor-internal duplicate (was generating same caveat per session)
  if (t === 'Review errors before repeating this workflow.') return true;
  // Pasted from forums/Reddit/etc. — block when "your post" / "Rule N:" patterns dominate
  if (/Rule \d+:/.test(t.slice(0, 200)) && /your (post|submission)/i.test(t)) return true;
  // Stack-trace like
  if (/^\s*at\s+\w+.*\(.*:\d+:\d+\)/m.test(t.slice(0, 500))) return true;
  return false;
}

// Detect if a session is entirely/mostly automated (scheduled task, CI, etc.)
export function isAutomatedSession(firstUserText: string): boolean {
  return /^\s*<scheduled-task|^\s*<automated-/.test(firstUserText);
}

export function parseSessionFile(jsonlPath: string): ParsedSession | null {
  const raw = readFileSync(jsonlPath, 'utf8');
  const lines = raw.split('\n').filter(Boolean);
  if (lines.length === 0) return null;

  let session_id = '';
  let project_cwd = '';
  let git_branch: string | undefined;
  let minTs = Number.MAX_SAFE_INTEGER;
  let maxTs = 0;

  const turns: SessionTurn[] = [];
  const file_ops: ParsedSession['file_ops'] = [];
  let turn_count_user = 0;
  let turn_count_assistant = 0;
  let errors_count = 0;

  // Track last meaningful user text so we can attach it as context to file edits
  let lastUserText = '';

  // First pass: build turns
  // Also keep a map of tool_use_id → (turn_uuid, name, input) so we can join results
  const toolUseIndex = new Map<string, { turn_uuid: string; name: string; input: any; timestamp: number }>();

  for (const line of lines) {
    let event: any;
    try { event = JSON.parse(line); } catch { continue; }

    if (!session_id && event.sessionId) session_id = event.sessionId;
    if (!project_cwd && event.cwd) project_cwd = event.cwd;
    if (!git_branch && event.gitBranch) git_branch = event.gitBranch;

    const ts = event.timestamp ? Math.floor(new Date(event.timestamp).getTime() / 1000) : 0;
    if (ts > 0) {
      if (ts < minTs) minTs = ts;
      if (ts > maxTs) maxTs = ts;
    }

    if (event.type !== 'user' && event.type !== 'assistant') continue;
    if (event.isMeta || event.isSidechain) continue;

    const message = event.message;
    if (!message) continue;
    const role = message.role as 'user' | 'assistant';
    if (role !== 'user' && role !== 'assistant') continue;

    const text = extractTextFromContent(message.content);
    const tool_calls = role === 'assistant' ? extractToolCalls(message.content) : undefined;
    const tool_results = role === 'user' ? extractToolResults(message.content) : undefined;

    if (role === 'user') turn_count_user++;
    else turn_count_assistant++;

    if (tool_results) {
      for (const tr of tool_results) if (tr.is_error) errors_count++;
    }

    const turn: SessionTurn = {
      uuid: event.uuid ?? '',
      role,
      timestamp: ts,
      text,
      tool_calls,
      tool_results,
    };
    turns.push(turn);

    // Track latest user intent for "why" attribution
    if (role === 'user' && !isMetaOrNoise(text) && !tool_results) {
      lastUserText = text.trim();
    }

    // Capture file operations from assistant tool calls
    if (role === 'assistant' && tool_calls) {
      for (const call of tool_calls) {
        toolUseIndex.set(call.tool_use_id, {
          turn_uuid: turn.uuid,
          name: call.name,
          input: call.input,
          timestamp: ts,
        });

        const op = classifyToolOp(call.name);
        if (op && call.input?.file_path) {
          file_ops.push({
            operation: op,
            path: call.input.file_path,
            turn_uuid: turn.uuid,
            timestamp: ts,
            preceding_user_text: lastUserText.slice(0, 600),
            tool_input_preview: summarizeToolInput(call.name, call.input),
          });
        } else if (call.name === 'Bash' && typeof call.input?.command === 'string') {
          // capture git/build commands as 'bash' ops — no file_path but still useful
          const cmd = call.input.command as string;
          // extract file-like paths from the command if any, else store whole command
          file_ops.push({
            operation: 'bash',
            path: extractFirstPathFromCommand(cmd) ?? '(shell)',
            turn_uuid: turn.uuid,
            timestamp: ts,
            preceding_user_text: lastUserText.slice(0, 600),
            tool_input_preview: cmd.slice(0, 200),
          });
        }
      }
    }
  }

  if (!session_id || turns.length === 0) return null;

  return {
    session_id,
    project_cwd: project_cwd || '(unknown)',
    started_at: minTs === Number.MAX_SAFE_INTEGER ? 0 : minTs,
    ended_at: maxTs,
    git_branch,
    turns,
    file_ops,
    turn_count_user,
    turn_count_assistant,
    errors_count,
  };
}

function classifyToolOp(name: string): 'read' | 'edit' | 'write' | 'other' | null {
  if (name === 'Read') return 'read';
  if (name === 'Edit' || name === 'MultiEdit' || name === 'NotebookEdit') return 'edit';
  if (name === 'Write') return 'write';
  return null;
}

function summarizeToolInput(name: string, input: any): string {
  try {
    if (name === 'Edit') {
      const old_s = (input.old_string ?? '').toString();
      const new_s = (input.new_string ?? '').toString();
      return `OLD(${old_s.length}ch): ${old_s.slice(0, 80)}... NEW(${new_s.length}ch): ${new_s.slice(0, 80)}...`;
    }
    if (name === 'Write') {
      const c = (input.content ?? '').toString();
      return `WRITE(${c.length}ch): ${c.slice(0, 120)}...`;
    }
    if (name === 'Read') {
      return `READ ${input.file_path ?? ''}${input.offset ? ` +${input.offset}` : ''}`;
    }
    return JSON.stringify(input).slice(0, 200);
  } catch {
    return '';
  }
}

function extractFirstPathFromCommand(cmd: string): string | null {
  // heuristic: look for something that looks like a path in the command
  const m = cmd.match(/[A-Za-z]:[\\/][\w\-\.\\/]+|(?<![A-Za-z0-9])\.?\/?[\w\-\.]+\/[\w\-\.\/]+/);
  return m ? m[0] : null;
}

// Utility: project_cwd → project name (last path segment)
export function projectNameFromCwd(cwd: string): string {
  if (!cwd) return 'unknown';
  return cwd.replace(/\\/g, '/').replace(/\/$/, '').split('/').filter(Boolean).pop() ?? 'unknown';
}
